In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df=pd.DataFrame({
    'Color':['Red','Blue','Green','Blue','Green','Red','Blue','Red']

})
df.head()

   Color
0    Red
1   Blue
2  Green
3   Blue
4  Green

In [3]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [4]:
lbl_encoder.fit_transform(df[['Color']])

c:\Users\faith\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 0, 1, 2, 0, 2])

Ordinal Encoding

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
df=pd.DataFrame({
    'size':['small','medium','large','small','large','medium']
})
df.head()

     size
0   small
1  medium
2   large
3   small
4   large

In [10]:
ord_encoder=OrdinalEncoder(categories=[['small','medium','large']])
ord_encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [1.]])