In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [27]:
df=pd.read_csv('jio_mart_items.csv')
df.head(5)

,category,sub_category,href,items,price
0,Groceries,Fruits & Vegetables,https://www.jiomart.com/c/groceries/fruits-veg...,Fresh Dates (Pack) (Approx 450 g - 500 g),109.0
1,Groceries,Fruits & Vegetables,https://www.jiomart.com/c/groceries/fruits-veg...,Tender Coconut Cling Wrapped (1 pc) (Approx 90...,49.0
2,Groceries,Fruits & Vegetables,https://www.jiomart.com/c/groceries/fruits-veg...,Mosambi 1 kg,69.0
3,Groceries,Fruits & Vegetables,https://www.jiomart.com/c/groceries/fruits-veg...,Orange Imported 1 kg,125.0
4,Groceries,Fruits & Vegetables,https://www.jiomart.com/c/groceries/fruits-veg...,Banana Robusta 6 pcs (Box) (Approx 800 g - 110...,44.0

In [35]:
df.shape

(162313, 5)

In [28]:
df['category'].value_counts()

category
Home & Kitchen    60335
Groceries         46044
Fashion           26101
Electronics       19022
Beauty            10741
Jewellery            70
Name: count, dtype: int64

In [29]:
from sklearn.utils import resample
target=10000
home_kitchen=df[df['category']=='Home & Kitchen']
groceries=df[df['category']=='Groceries']
fashion=df[df['category']=='Fashion']
electronics=df[df['category']=='Electronics']
Beauty=df[df['category']=='Beauty']
Jewellery=df[df['category']=='Jewellery']

In [30]:
jewellery_upsampled=resample(
    Jewellery,
    replace=True,
    n_samples=target,
    random_state=42
)
balanced_df=pd.concat([
    home_kitchen,
    groceries,
    fashion,
    electronics,
    Beauty,
    jewellery_upsampled
    ])

In [31]:
balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [32]:
balanced_df['category'].value_counts()

category
Home & Kitchen    60335
Groceries         46044
Fashion           26101
Electronics       19022
Beauty            10741
Jewellery         10000
Name: count, dtype: int64

In [33]:
balanced_df.head()

,category,sub_category,href,items,price
0,Home & Kitchen,Kitchenware,https://www.jiomart.com/c/groceries/home-kitch...,Prime Bakers and Moulders Store Round Aluminiu...,540.0
1,Groceries,Staples,https://www.jiomart.com/c/groceries/staples/at...,Zemakk Steam Rice 1 Kg Each (Pack of 3),279.0
2,Jewellery,Fine Jewellery,https://www.jiomart.com/c/jewellery/fine-jewel...,Reliance Jewels Ag 99.9 8.73 gm Lakshmi Ganesh...,2318.0
3,Groceries,Mom & Baby Care,https://www.jiomart.com/c/groceries/mom-baby-c...,Saral Home Multi Velvet And Cotton Dinosaur Ac...,2199.0
4,Fashion,Women,https://www.jiomart.com/c/fashion/women/eyewea...,"Unisex Artificial leather Protective Case, Sli...",299.0

In [34]:
balanced_df.shape

(172243, 5)