In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [46]:
df=pd.read_csv('train.csv')
df.head(1)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500

In [47]:
null_counts = df.isnull().sum()
print(null_counts[null_counts > 0])

LotFrontage      259
Alley           1369
MasVnrType       872
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

In [48]:
df['Alley']=df['Alley'].fillna('None')
df['PoolQC']=df['PoolQC'].fillna('None')
df['MiscFeature']=df['MiscFeature'].fillna('None')
df['Fence']=df['Fence'].fillna('None')
df['FireplaceQu']=df['FireplaceQu'].fillna('None')
df['MasVnrType']=df['MasVnrType'].fillna('None')
df['MasVnrArea']=df['MasVnrArea'].fillna(0)
df['GarageType']=df['GarageType'].fillna('None')
df['GarageFinish']=df['GarageFinish'].fillna('None')
df['GarageQual']=df['GarageQual'].fillna('None')
df['GarageCond']=df['GarageCond'].fillna('None')
df['GarageYrBlt']=df['GarageYrBlt'].fillna(0)
df['Electrical']=df['Electrical'].fillna(df['Electrical'].mode()[0])
df['BsmtQual']=df['BsmtQual'].fillna('None')
df['BsmtCond']=df['BsmtCond'].fillna('None')
df['BsmtExposure']=df['BsmtExposure'].fillna('None')
df['BsmtFinType1']=df['BsmtFinType1'].fillna('None')
df['BsmtFinType2']=df['BsmtFinType2'].fillna('None')
df['LotFrontage']=df['LotFrontage'].fillna(df['LotFrontage'].median())

In [34]:
df[['MasVnrType', 'MasVnrArea']].head(20)

   MasVnrType  MasVnrArea
0     BrkFace       196.0
1         NaN         0.0
2     BrkFace       162.0
3         NaN         0.0
4     BrkFace       350.0
5         NaN         0.0
6       Stone       186.0
7       Stone       240.0
8         NaN         0.0
9         NaN         0.0
10        NaN         0.0
11      Stone       286.0
12        NaN         0.0
13      Stone       306.0
14    BrkFace       212.0
15        NaN         0.0
16    BrkFace       180.0
17        NaN         0.0
18        NaN         0.0
19        NaN         0.0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             0 non-null      int64
 1   MSSubClass     0 non-null      int64
 2   MSZoning       0 non-null      object
 3   LotFrontage    0 non-null      float64
 4   LotArea        0 non-null      int64
 5   Street         0 non-null      object
 6   Alley          0 non-null      object
 7   LotShape       0 non-null      object
 8   LandContour    0 non-null      object
 9   Utilities      0 non-null      object
 10  LotConfig      0 non-null      object
 11  LandSlope      0 non-null      object
 12  Neighborhood   0 non-null      object
 13  Condition1     0 non-null      object
 14  Condition2     0 non-null      object
 15  BldgType       0 non-null      object
 16  HouseStyle     0 non-null      object
 17  OverallQual    0 non-null      int64
 18  OverallCond    0 non-null      int64
 19  YearBuilt      0 non-null      int64
 20  YearRemodAdd   0 non-null      int64
 21  RoofStyle      0 non-null      object
 22  RoofMatl       0 non-null      object
 23  Exterior1st    0 non-null      object
 24  Exterior2nd    0 non-null      object
 25  MasVnrType     0 non-null      object
 26  MasVnrArea     0 non-null      float64
 27  ExterQual      0 non-null      object
 28  ExterCond      0 non-null      object
 29  Foundation     0 non-null      object
 30  BsmtQual       0 non-null      object
 31  BsmtCond       0 non-null      object
 32  BsmtExposure   0 non-null      object
 33  BsmtFinType1   0 non-null      object
 34  BsmtFinSF1     0 non-null      int64
 35  BsmtFinType2   0 non-null      object
 36  BsmtFinSF2     0 non-null      int64
 37  BsmtUnfSF      0 non-null      int64
 38  TotalBsmtSF    0 non-null      int64
 39  Heating        0 non-null      object
 40  HeatingQC      0 non-null      object
 41  CentralAir     0 non-null      object
 42  Electrical     0 non-null      object
 43  1stFlrSF       0 non-null      int64
 44  2ndFlrSF       0 non-null      int64
 45  LowQualFinSF   0 non-null      int64
 46  GrLivArea      0 non-null      int64
 47  BsmtFullBath   0 non-null      int64
 48  BsmtHalfBath   0 non-null      int64
 49  FullBath       0 non-null      int64
 50  HalfBath       0 non-null      int64
 51  BedroomAbvGr   0 non-null      int64
 52  KitchenAbvGr   0 non-null      int64
 53  KitchenQual    0 non-null      object
 54  TotRmsAbvGrd   0 non-null      int64
 55  Functional     0 non-null      object
 56  Fireplaces     0 non-null      int64
 57  FireplaceQu    0 non-null      object
 58  GarageType     0 non-null      object
 59  GarageYrBlt    0 non-null      float64
 60  GarageFinish   0 non-null      object
 61  GarageCars     0 non-null      int64
 62  GarageArea     0 non-null      int64
 63  GarageQual     0 non-null      object
 64  GarageCond     0 non-null      object
 65  PavedDrive     0 non-null      object
 66  WoodDeckSF     0 non-null      int64
 67  OpenPorchSF    0 non-null      int64
 68  EnclosedPorch  0 non-null      int64
 69  3SsnPorch      0 non-null      int64
 70  ScreenPorch    0 non-null      int64
 71  PoolArea       0 non-null      int64
 72  PoolQC         0 non-null      object
 73  Fence          0 non-null      object
 74  MiscFeature    0 non-null      object
 75  MiscVal        0 non-null      int64
 76  MoSold         0 non-null      int64
 77  YrSold         0 non-null      int64
 78  SaleType       0 non-null      object
 79  SaleCondition  0 non-null      object
 80  SalePrice      0 non-null      int64
dtypes: float64(3), int64(35), object(43)
memory usage: 0.0+ bytes

In [49]:
null_counts = df.isnull().sum()
print(null_counts[null_counts > 0])

Series([], dtype: int64)